# This is a config for E2B sandbox template.
# You can use template ID (ikqi1yiqk4zl20fympnn) or template name (frambit-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("frambit-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("frambit-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('frambit-nextjs')

team_id = "6dc657bc-9881-444b-a98f-ae41e553b267"
start_cmd = "bash /compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "frambit-nextjs"
template_id = "ikqi1yiqk4zl20fympnn"
